### ISSUE TITLE
BYGRichTextBlock resizes when zooming in and out in UMG editor

### ISSUE THREAD

**Issue by Grimeh** [BraceYourselfGames/UE4-BYGRichText#1]
![rt_sizing](https://user-images.githubusercontent.com/1988562/123585022-8b30d900-d836-11eb-84b1-7f75132f8752.gif)
(the top box is a BYG Rich Text block, the bottom is a builtin rich text block with the desired behaviour)

### Repro info
I have a UMG hierarchy that looks like:
`Canvas/Canvas/Horizontal Box/Vertical Box/BYG Rich Text Block`
When scrolling in and out in the UMG editor, the rich text block will appear to resize itself depending on the zoom level. When you compile the user widget or change a property on the rich text block, everything goes back to normal (the text block goes back to one line using the example gif above).

My best guess is this has something to do with DPI or "desired size", but I'm not familiar enough with UMG/Slate's layout system to properly guess.

**Comment by drichardson** [comment]
Can you show the modified properties for each widget in the hierarchy? I'm interesting to see where _Size to Content_ is used and where _Auto Wrap Text_ is used. I've seen similar issues with text boxes during resizing.

**Comment by Grimeh** [comment]
Sure thing, here are screenshots for each widget in the immediate hierarchy. The only modifications are in the slot properties.

CanvasPanel_0 - no modifications, sized to 1920x1080, DPI scale 1.0. Can repro @ 720 with DPI 0.67.

CanvasPanel_1
![image](https://user-images.githubusercontent.com/1988562/123713816-56ba2d00-d8c9-11eb-9540-93133a0a2c75.png)

HorizontalBox_0
![image](https://user-images.githubusercontent.com/1988562/123714011-abf63e80-d8c9-11eb-8cb6-765700f824da.png)

VerticalBox_103
![image](https://user-images.githubusercontent.com/1988562/123714053-bd3f4b00-d8c9-11eb-8c67-dded5e4f9bad.png)

ChoiceExample - BYGRichTextBlock
![image](https://user-images.githubusercontent.com/1988562/123714120-d647fc00-d8c9-11eb-953e-59b6d4125daa.png)

**Comment by benui-dev** [comment]
This also happens in-game. Even if there is enough space, sometimes it is wrapped, sometimes it is not.

I have confirmed that this happens with the default text widget when autowrap is enabled and it is set to "auto" in a horizontal box. In the gif the top one is a regular UE4 text block, the one below is a BYG Rich Text Box

![](https://i.imgur.com/Bk4xZXE.gif)

**Comment by Grimeh** [comment]
Huh, my mistake then!
Thanks for clearing that up, sorry to waste time on a non-issue.
